### ISSUE TITLE
Add option to not have all methods selected in lsp-java-generate-overrides

### ISSUE THREAD

**Issue by dakra** [emacs-lsp/lsp-java#147]
When calling `lsp-java-generate-overrides` (from
`lsp-execute-code-action`) almost always I only want to implement 1
(or a few) methods but by default all possible override methods are
selected. So let's say there are 20 possible methods to override and
I want to implement 1, I first have to de-select 19.

I would like a config option to have this behavior toggled,
or even better, by default have all de-selected and with a prefix
command have all selected.

Thanks for making this package and making it possible for me
to work on Java code from Emacs :)

**Comment by yyoncho** [comment]
I am going to create a helm interface(helm will be used if present) which has the option to select/deselect all. The issue is that the completing-read-multiple that ships with emacs is not very user-friendly(hard to figure out how it works and hard to use) and the ad-hoc solution that I have implemented is not very user-friendly(hard to use) in some of the cases(like what you have described).

**Comment by dakra** [comment]
Nice, thanks. Maybe I find some time to make an ivy version of this.

**Comment by jypma** [comment]
Would it still not make sense to default to not selecting anything (or just allowing 1 method) when not using ivy nor helm? I actually can't even seem to figure out how to make `completing-read-multiple` accept its input and generate the methods: pressing [Enter] just toggles options, and I can see no other keybindings...

By the way, ido, ido-vertical and ido's fuzzy matching work fine with `completing-read-multiple`.

**Comment by yyoncho** [comment]
@jypma ok, I will then delete the ad-hoc implementation and I will rely on built-in implementation.

**Comment by yauhen-l** [comment]
Hi @yyoncho,
right now this is really painful. It preselects all 37 methods in my use-case and as mentioned by @jypma there is no keybinding to deselect all. What is even worse on every selection helm cursor jumps to the very top of a list.

**Comment by yyoncho** [comment]
Did you try `M-M`? It selects/deselects all in helm.

**Comment by yauhen-l** [comment]
Nothing happens.
`C-h m` does show this binding exists when helm buffer is active.
Packages:
```
  helm               20200220.1651
  lsp-mode           6.2.1
  lsp-java           2.2
```

**Comment by yyoncho** [comment]
I will take a look tomorrow - it may be spacemacs setting this shortcut

**Comment by elfehr** [comment]
For future people who stumble here and have neither helm nor ivy (in my case the completion is handled by `vertico`): the function determining this behavior is `lsp-java--completing-read-multiple`.

I overrode it, removing the helm and ivy-specific parts and setting `deps` to `nil` instead of `initial-selection`, so that initially nothing is selected:

``` elisp
(use-package lsp-java
  :config
  (defun lsp-java--completing-read-empty (message items ignored-initial-selection)
    "Without helm / ivy, start with everything deselected by default."
    (let ((deps nil) dep)
      (while (setq dep (cl-rest (lsp--completing-read
                                 (if deps
                                     (format "%s (selected %s): " message (length deps))
                                   (concat message ": "))
                                 items
                                 (-lambda ((name . id))
                                   (if (-contains? deps id)
                                       (concat name " ✓")
                                     name)))))
        (if (-contains? deps dep)
            (setq deps (remove dep deps))
          (cl-pushnew dep deps)))
      deps))
  :advice (:override lsp-java--completing-read-multiple lsp-java--completing-read-empty))
```
